[package]
name = "cclone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"


[profile.release]
lto = true
strip = true
opt-level = "z" 
panic = "abort"


[profile.dev]
